import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

const fetcherSDL = (query) =>
  fetch('/api/graphqlSDL', {
    method: 'POST',
    headers: {
      'Content-type': 'application/json',
    },
    body: JSON.stringify({ query }),
  })
    .then((res) => res.json())
    .then((json) => json.data)

const fetcherType = (query) =>
  fetch('/api/graphql', {
    method: 'POST',
    headers: {
      'Content-type': 'application/json',
    },
    body: JSON.stringify({ query }),
  })
    .then((res) => res.json())
    .then((json) => json.data)

const Home: NextPage = () => {
  const { data: sdl } = useSWR('{ usersdl { id title description } }', fetcherSDL)
  const { data: typegql } = useSWR('{ user { id title description } }', fetcherType)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          {JSON.stringify(sdl)}
        </p>

        <p className={styles.description}>
          {JSON.stringify(typegql)}
        </p>

      </main>

    </div>
  )
}

export default Home
